<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Домой',
    'Brands' =>' Бренды',
    'Categories' => 'Категории',
    'Characteristics products' => 'Характеристики',
    'Clean cache' => 'Кэш',
    'Delivery' => 'Доставка',
    'Orders' => 'Заказы',
    'Products' => 'Продукты',
    'Tags' => 'Тэги',
    'Users' => 'Пользователи',
    'recommended' => 'Рекомендованный товар',
    'Continue Shopping' => 'Продолжить покупки',
    'Empty baskets' => 'Очистить корзину',
    'Shopping Cart' => 'Корзина покупок',
    'Compare products' => 'Сравнение продуктов',
    'My Account' => 'Аккаунт',
    'Wish List' => 'Избранное',
    'Checkout' => 'Оформление заказа',
    'Catalog' => 'Каталог',
    'Blog' => 'Блог',
    'Contact' => 'Контакт',
    'Empty compare'=> 'Удалить сравнения',
    'Pages' => 'Страницы'
];
